<a href="https://colab.research.google.com/github/x1001000/Colab-Notebooks/blob/main/cosine_similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google import genai
from google.genai import types
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

client = genai.Client()

In [2]:
texts = [
    '條紋',
    '襯衫',
    '條紋襯衫',
    '無條紋的襯衫',
]

In [3]:
import pandas as pd

result = [
    np.array(e.values) for e in client.models.embed_content(
        model="gemini-embedding-001",
        contents=texts,
        config=types.EmbedContentConfig(task_type="SEMANTIC_SIMILARITY")).embeddings
]
print('gemini-embedding-001 嵌入模型\n\n的輸出向量為例\n\n四個詞彙的兩兩相似度由高至低\n')
# Calculate cosine similarity. Higher scores = greater semantic similarity.

embeddings_matrix = np.array(result)
similarity_matrix = cosine_similarity(embeddings_matrix)

similarity_results = []
for i, text1 in enumerate(texts):
    for j in range(i + 1, len(texts)):
        text2 = texts[j]
        similarity = similarity_matrix[i, j]
        similarity_results.append((similarity, text1, text2))

# Sort the results by similarity in descending order
similarity_results.sort(key=lambda x: x[0], reverse=True)

similarity_df = pd.DataFrame(similarity_results, columns=['Similarity', 'Text 1', 'Text 2'])
display(similarity_df)

gemini-embedding-001 嵌入模型

的輸出向量為例

四個詞彙的兩兩相似度由高至低

   Similarity Text 1  Text 2
0    0.948232     襯衫    條紋襯衫
1    0.943101     襯衫  無條紋的襯衫
2    0.935395     條紋    條紋襯衫
3    0.920250   條紋襯衫  無條紋的襯衫
4    0.856336     條紋      襯衫
5    0.848934     條紋  無條紋的襯衫

In [4]:
import pandas as pd

result = [
    np.array(e.values) for e in client.models.embed_content(
        model="gemini-embedding-2-preview",
        contents=texts,
        config=types.EmbedContentConfig(task_type="SEMANTIC_SIMILARITY")).embeddings
]
print('gemini-embedding-2-preview 嵌入模型\n\n的輸出向量為例\n\n四個詞彙的兩兩相似度由高至低\n')
# Calculate cosine similarity. Higher scores = greater semantic similarity.

embeddings_matrix = np.array(result)
similarity_matrix = cosine_similarity(embeddings_matrix)

similarity_results = []
for i, text1 in enumerate(texts):
    for j in range(i + 1, len(texts)):
        text2 = texts[j]
        similarity = similarity_matrix[i, j]
        similarity_results.append((similarity, text1, text2))

# Sort the results by similarity in descending order
similarity_results.sort(key=lambda x: x[0], reverse=True)

similarity_df = pd.DataFrame(similarity_results, columns=['Similarity', 'Text 1', 'Text 2'])
display(similarity_df)

gemini-embedding-2-preview 嵌入模型

的輸出向量為例

四個詞彙的兩兩相似度由高至低

   Similarity Text 1  Text 2
0    0.875992     襯衫    條紋襯衫
1    0.841801     條紋    條紋襯衫
2    0.831482   條紋襯衫  無條紋的襯衫
3    0.783443     襯衫  無條紋的襯衫
4    0.748881     條紋      襯衫
5    0.723957     條紋  無條紋的襯衫